# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dutis < Formula
  desc "A command-line tool to select default applications, based on duti"
  homepage "https://github.com/tsonglew/dutis"
  version "0.1.0"
  license "MIT"

  depends_on "git"
  depends_on "go"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tsonglew/dutis/releases/download/v0.1.0/dutis_Darwin_arm64.tar.gz"
      sha256 "b583b86cf7ae112054790ce678b130762417894ab47eda3d605d36badb4ea69b"

      def install
        bin.install "dutis"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tsonglew/dutis/releases/download/v0.1.0/dutis_Darwin_x86_64.tar.gz"
      sha256 "9e70e874051837f0453e55236e883888149a77fc5a9c6551e22b3c938f2bfbf0"

      def install
        bin.install "dutis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tsonglew/dutis/releases/download/v0.1.0/dutis_Linux_x86_64.tar.gz"
      sha256 "f89b31e2e90ed495e704cf3e6bde9d97232b90c012f49055455d8ea1e1a7820b"

      def install
        bin.install "dutis"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tsonglew/dutis/releases/download/v0.1.0/dutis_Linux_arm64.tar.gz"
      sha256 "191dd1b08b11d550e4714667a2cf9bc1d1e1e520041486242e480ab94435f339"

      def install
        bin.install "dutis"
      end
    end
  end
end
